extends RefCounted
## Player-facing Chinese; source IDs and semantic tags stay language independent.
const WORDS={
 "Ms. B____":"贝____老师","E. M______":"艾·莫______","E____":"艾____",
 "Kenneth Grahame · The Wind in the Willows (1908)":"肯尼斯·格雷厄姆《柳林风声》（1908）",
 "LETTER OFFICE / 雨后的书信事务所":"雨后的书信事务所",
 "RAIN IN THE DROP BOX":"雨中的投信箱",
 "PAPER DRAWER / 小镇的纸":"纸片抽屉 · 小镇的纸",
 "HARBOR LANE / 街道名录":"海港巷 · 街道名录",
 "SOLMERE RECORDS / 活动册":"索尔米尔唱片店 · 活动册",
 "SCHOOL ARCHIVE / 文学科":"学校档案 · 文学科",
 "FOR THE LETTER OFFICE":"致书信事务所",
 "For the Letter Office":"致书信事务所",
 "HELP ME SAY IT":"替我说出口",
 "PAPER DRAWER":"纸片抽屉",
 "FIELD NOTES":"工作札记",
 "SCHOOL ARCHIVE":"学校档案",
 "DIRECTORY":"小镇名录",
 "INCOMING":"来信托盘",
 "Sent into Solmere. 信在路上了。":"寄进海风里。信在路上了。",
 "Solmere · Letter Office":"索尔米尔 · 书信事务所",
 "Elena Moreau":"艾琳娜·莫罗",
 "Nico Alvarez":"尼科·阿尔瓦雷斯",
 "N. Alvarez":"N. 阿尔瓦雷斯",
 "Ms. Bell":"贝尔老师",
 "Mara":"玛拉","MARA":"玛拉",
 "Theo Ward":"西奥·沃德","THEO":"西奥","Theo":"西奥",
 "June 17":"6 月 17 日","JUNE 17":"6 月 17 日","JUNE 18":"6 月 18 日",
 "June":"朱恩","JUNE":"朱恩",
 "Summer Static  ◯":"夏日杂音  ◯","Summer Static":"《夏日杂音》","SUMMER STATIC":"夏日杂音",
 "Solmere Records":"索尔米尔唱片店","SOLMERE RECORDS":"索尔米尔唱片店",
 "14 Harbor Lane":"海港巷 14 号","14 HARBOR LANE":"海港巷 14 号","16 Harbor Lane":"海港巷 16 号",
 "Lena Moss — Far Shore":"莉娜·莫斯 —《远岸》","Inez Duarte":"伊内兹·杜阿尔特",
 "LEMON CAFÉ MENU":"柠檬咖啡馆 · 菜单","LEMON CAFÉ":"柠檬咖啡馆","Lemon Café":"柠檬咖啡馆",
 "SOLMERE RAIL":"索尔米尔铁路","SOLMERE DIRECTORY":"索尔米尔名录",
 "LITERATURE DEPARTMENT":"文学教研室","LITERATURE · 1998":"文学课本 · 1998",
 "MAYA'S BOOKSHOP":"玛雅的书店","SOLMERE DAILY":"索尔米尔日报",
 "SOLMERE → MARSEILLE":"索尔米尔 → 马赛",
 "Don't make yourself\nsmaller just because\nthe room is.":"不要因为房间太小，\n就让自己也\n变得渺小。",
 "Don't make it sound like":"别让它听起来像",
 "Please don't make it\nsound like I'm\ncoming home.":"请不要让这封信\n听起来像是\n我要回家了。",
 "I finally did it.\nDon't turn it into\nan apology.":"我终于做到了。\n别把它写成\n一封道歉信。",
 "You wrote something\nin the margin\nwhen I was fifteen.\nI kept it.":"我十五岁那年，\n您在课本页边\n写过一句话。\n我一直留着。",
 "She will remember.":"她会记得的。",
 "Fifteen years old.":"十五岁那年。",
 "same table next year?":"明年，还坐这张桌子吗？",
 "N. said I never would.":"N. 说，我不敢。",
 "TABLE 6":"6 号桌","LEMON SODA × TWO":"柠檬汽水 × 两杯","2 drinks · 6.00":"饮品两杯 · 6.00",
 "07:42    SEAT 18":"07:42    18 号座",
 "OPEN MIC":"开放麦之夜","JULY 14":"7 月 14 日","Host:":"主持人：",
 "Thursday · reading room":"星期四 · 阅览室",
 "SIDE B":"唱片 B 面","After 11":"十一点以后","First Light":"第一缕光",
 "ADDRESS":"收件地址","FROM  ":"来自  ","FROM ":"来自 ","TO  ":"寄给  ","TO ":"寄给 ","TO 的位置":"收件人一栏",
 "A QUIETER SUMMER\nAnother June at the harbour.\nThe first ferry leaves at six.":"安静一点的夏天\n海港又迎来一个六月。\n清晨六点，第一班渡船离岸。",
 "There is nothing\nhalf so much worth doing\nas simply messing about\nin boats.":"没有什么事\n比单纯地在船上\n消磨时光\n更值得做了。",
 "STILL HERE\nRETURN · SIDE A\nLIVE BY THE SEA":"依然在这里\n归来 · 唱片 A 面\n海边现场",
 "LEMON / MINT\nTWO LITTLE TABLES\nSOME PLACES STAY":"柠檬 / 薄荷\n两张小桌\n有些地方一直都在",
 "DON'T MAKE YOURSELF SMALLER":"别让自己变得渺小",
 "SOME PLACES STAY":"有些地方一直都在","some places stay":"有些地方一直都在",
 "I FINALLY DID IT":"我终于做到了","I REMEMBER":"我记得",
 "ANOTHER JUNE":"又一个六月","REMEMBERED":"被记得","REMEMBER":"记得",
 "not HOME":"不是回家","ON STAGE":"站上舞台","I KEPT IT":"我一直留着",
 "THE MARGIN":"那句页边批注","THANK YOU":"谢谢你","FIFTEEN":"十五岁",
 "SOUND LIKE":"听起来像","PLEASE":"请","ONE WAY":"单程","QUIETER":"安静一点",
 "MARSEILLE":"马赛","SOLMERE":"索尔米尔","Solmere":"索尔米尔",
 "Lighthouse":"灯塔","Lemon":"柠檬","Train":"火车",
 "STILL":"依然","still":"依然","RETURN":"归来","SORRY":"对不起","GOODBYE":"告别",
 "HOME":"家","LEMON":"柠檬","TWO":"两个人","HERE":"这里","AGAIN":"再一次","ROOM":"余地",
 "I KEEP":"我总是","LEAVING":"离开","before":"在……之前","ANYTHING":"任何事物","CAN BECOME":"能够成为",
 "TODAY":"今天","I LEFT":"我留着","A LIGHT":"一盏灯","LIGHT":"灯","ON":"亮着","FOR MYSELF":"给自己","MYSELF":"自己",
 "THE LAST":"最后一班","FERRY":"渡船","WAITED":"等了","ONE MORE":"多一分","MINUTE":"钟",
 "I AM":"我正在","LEARNING":"学习","TO SAY":"说一句","NO":"不","SOFTLY":"轻轻地",
 "SOME DAYS":"有些日子","THE SEA":"这片海","IS ENOUGH":"就足够了","SEA":"海","ENOUGH":"足够","DAYS":"日子",
 "DAD KEPT":"爸爸留着","MY DRAWING":"我的画","IN HIS":"在他的","WORK COAT":"工作服里","DRAWING":"画","KEPT":"留着","COAT":"外套",
 "I MISS":"我想念","THE PERSON":"那个人","I WAS":"曾经的我","BEFORE":"在此之前","I KNEW":"我明白","KNEW":"明白","MISS":"想念",
 "AT SIX":"清晨六点","THE BAKERY":"面包房","KNOWS":"记得","MY NAME":"我的名字","SIX":"六点","NAME":"名字",
 "MY OLD":"我的旧","RADIO":"收音机","FINDS":"找得到","A SONG":"一首歌","SONG":"歌",
 "WE SAT":"我们坐着","WITHOUT":"没有","FIXING":"解决","SAT":"坐着",
 "THE GARDEN":"花园","TOOK":"慢慢地","ITS TIME":"生长","SO CAN":"我也可以","GARDEN":"花园","TIME":"时间",
 "I SAVED":"我留了","A SEAT":"一个座位","FOR":"给","TOMORROW":"明天","SEAT":"座位","SAVED":"留下",
 "例如：just / can change shape":"例如：只是 / 也可以换一种模样",
 "I":"我"
}
static var keys:Array=[]
static func show(value:String) -> String:
 if WORDS.has(value):return WORDS[value]
 if keys.is_empty():
  keys=WORDS.keys();keys.sort_custom(func(a,b):return a.length()>b.length())
 var out=value
 for key in keys:
  # Single English words must not replace letters inside other words.
  if key.length()<4:continue
  out=out.replace(key,str(WORDS[key]))
 return out
