"""Portable Windows launcher; starts a loopback post office when needed."""
import argparse
import configparser
import hashlib
import json
import os
from pathlib import Path
import subprocess
import shutil
import sys
import time
from urllib.request import urlopen

ROOT=Path(__file__).resolve().parent.parent
STATE=Path(os.environ.get('LOCALAPPDATA',str(Path.home())))/'CollageLetterServer'
STATE.mkdir(parents=True,exist_ok=True)
FLAGS=subprocess.CREATE_NO_WINDOW if os.name=='nt' else 0


def import_signature(root=None):
    """Identify source changes without including files generated by imports."""
    root=ROOT if root is None else Path(root)
    candidates=[root/'project.godot']
    candidates.extend((root/'assets').rglob('*'))
    fingerprint=hashlib.sha256()
    fingerprint.update(b'collage-source-import-v1\n')
    for path in sorted(candidates):
        relative=path.relative_to(root)
        if (not path.is_file() or '.godot' in relative.parts
                or path.suffix.lower() in {'.import','.uid'}):
            continue
        metadata=path.stat()
        record=[relative.as_posix(),metadata.st_size,metadata.st_mtime_ns]
        fingerprint.update(json.dumps(record,ensure_ascii=False,separators=(',',':')).encode('utf-8'))
        fingerprint.update(b'\n')
    return fingerprint.hexdigest()


def ensure_local_server():
    try:
        with urlopen('http://127.0.0.1:8787/health',timeout=1) as response:
            if json.load(response).get('service')=='collage-letter':
                return
    except (OSError,ValueError):
        pass
    log=(STATE/'server.log').open('a',encoding='utf-8')
    subprocess.Popen([sys.executable,str(ROOT/'server/app.py')],cwd=ROOT,
                     stdout=log,stderr=log,creationflags=FLAGS)
    log.close()
    for _ in range(30):
        try:
            with urlopen('http://127.0.0.1:8787/health',timeout=.3) as response:
                if json.load(response).get('service')=='collage-letter':
                    return
        except (OSError,ValueError):
            time.sleep(.1)


def launch(profile=None, showcase=False):
    config=configparser.ConfigParser()
    config.read(ROOT/'network.cfg',encoding='utf-8')
    url=config.get('server','url',fallback='http://127.0.0.1:8787').strip('"')
    if not showcase and url.rstrip('/')=='http://127.0.0.1:8787':
        ensure_local_server()
    bundled=ROOT/'runtime/Godot.exe'
    engine=str(bundled) if bundled.exists() else os.environ.get('GODOT_BIN') or shutil.which('godot') or shutil.which('godot4')
    if not engine:
        raise SystemExit('Install Godot 4.5.1+ and add godot/godot4 to PATH, or set GODOT_BIN to its executable.')
    # Import new or changed source assets too when refreshing an existing
    # portable directory. Godot's generated metadata must not invalidate this.
    marker=ROOT/'.godot/open-pack-import-v4'
    signature=import_signature()
    try:
        imported_signature=marker.read_text(encoding='utf-8').strip()
    except (OSError,UnicodeError):
        imported_signature=''
    if imported_signature!=signature:
        with (STATE/'import.log').open('w',encoding='utf-8') as log:
            command=[engine,'--headless','--editor','--path',str(ROOT),'--import','--quit']
            # Godot 4.5 can fail while shutting down its first parallel import.
            # Retry the cached import once; only a successful run may launch.
            for attempt in range(2):
                result=subprocess.run(command,cwd=ROOT,stdout=log,stderr=log,creationflags=FLAGS)
                if result.returncode==0:
                    break
                if attempt==1:
                    raise subprocess.CalledProcessError(result.returncode,command)
        marker.parent.mkdir(parents=True,exist_ok=True)
        marker.write_text(signature+'\n',encoding='utf-8')
    command=[engine,'--path',str(ROOT)]
    if profile:
        command+=['--',f'--profile={profile}']
    if showcase:
        command+=['--showcase','--lang=zh']
    with (STATE/f'game-{profile or "default"}.log').open('w',encoding='utf-8') as log:
        subprocess.Popen(command,cwd=ROOT,stdout=log,stderr=log)


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--demo',action='store_true')
    parser.add_argument('--showcase',action='store_true')
    parser.add_argument('--server-only',action='store_true')
    args=parser.parse_args()
    if args.server_only:
        ensure_local_server()
    elif args.demo:
        launch('Player-A'); launch('Player-B')
    elif args.showcase:
        launch('Solmere-Showcase-20260927',showcase=True)
    else:
        launch()
